//  console.log([ ] + 1 + 2)
//  alert( "1"[0] )
//  console.log(2 && 1 && null && 0 && undefined)
//  alert( null || 2 && 3 || 4 )
// alert( +"Infinity" )
// console.log( 0 || "" || 2 || undefined || true || falsе )